### ISSUE TITLE
PyCharm Complaints

### ISSUE THREAD

**Issue by Will-Cooper** [dr-rodriguez/AstrodbKit2#31]
Couple of things my PyCharm started complaining about:
Class Database having unresolved attribute "Sources"; e.g in. 
```
db = Database(db_file)
db.query(db.Sources).count()
```
Then, ```db.search_object``` having unexpected argument, e.g. ```db.search_object('twa 27', fmt='pandas').source.values```
Although the code itself runs fine as expected...

**Comment by Will-Cooper** [comment]
I agree on the former, just PyCharm being a pain.  
Sorry I forgot the details on the second bit! PyCharm highlights the second argument ```fmt='pandas'``` as if it's an unexpected argument. I did upgrade astrodbkit2 so perhaps PyCharm hasn't realised I've done that yet...

**Comment by Will-Cooper** [comment]
Okay the ```fmt='pandas'``` issue has gone away. In addition, there is a dumb workaround for the PyCharm complaining about unresolved attributes just by creating a wrapper class specific to the user's database, for example:  
```
class SimpleDB(Database):
    Sources = None
````  
Might be a useful thing to mention in the docs, just as a quality of life thing for fancy IDE users?

**Comment by dr-rodriguez** [comment]
Your suggestion would work but it is a lot of work and defeats the purpose of having AstrodbKit2 dynamically figure out what the tables are. 

My recommendation would be to change the IDE settings. When you hover over the warning in PyCharm (and I imagine in other IDEs) you get the option of what to do with warnings like these. There is an option to ignore unresolved attributes from `astrodb.Database` which is the best approach here. If you want to undo that or expand on it, you can do so in the preferences screen looking at Editor -> Inspections -> Python -> Unresolved references

![PyCharm_unresolvedrefs](https://user-images.githubusercontent.com/13004332/112162235-4146b000-8bc2-11eb-92e7-f589ac3b8f28.png)
