### ISSUE TITLE
Investigate slowness of building in Windows

### ISSUE THREAD

**Issue by dr-rodriguez** [dr-rodriguez/AstrodbKit2#40]
When loading the database from source in Windows, the execution time is much slower, easily 20x or so.
Some things to investigate: 
Does running a linux VM/container fix this (ie, is this a Windows limitation?) 
Are there notes on performance with SQLAlchemy or similar for Windows? 
Can we leverage things like `multiprocessor` to speed this up?

**Comment by blackwer** [comment]
Some investigation with `cProfile` showed that the slowdown is related to `sqlite3` commits. One solution would queue up more transactions between commits, but a simple solution is to just create the database in memory, then flush it to disk and use that. Submitting a PR for it soon.
