### ISSUE TITLE
Make new IRAF loader

### ISSUE THREAD

**Issue by kelle** [dr-rodriguez/AstrodbKit2#52]
Make a loader and identifier for an IRAF FITS file that has multiple spectra AND a linear wavelength solution which needs to be calculated.  This is a slight modification of the existing `wcs1d-fits` identifer/loader in specutils except these files have NAXIS > 1.

name = `wcs1d_multispec`

**Comment by dr-rodriguez** [comment]
Example file: https://s3.amazonaws.com/bdnyc/optical_spectra/U10929.fits
This has WCSDIM=3, use the `wcs1d-fits` loader as a base for this.

**Comment by kelle** [comment]
Other examples:
- http://simple-bd-archive.org/solo_result/BRI%20B1222-1222
- http://simple-bd-archive.org/solo_result/2MASS%20J01231125-6921379
